# Generated by Django 5.1.7 on 2025-03-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor_number',
            field=models.IntegerField(default=1),
        ),
    ]
