# Generated by Django 5.1.7 on 2025-03-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='room_types/default.jpg', upload_to='room_types/'),
        ),
    ]
