# Generated by Django 5.1.7 on 2025-04-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_service_bookingservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменено'),
        ),
    ]
