# Generated by Django 5.1.7 on 2025-04-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата Обновления'),
        ),
    ]
